<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">
	<head>
		<meta http-equiv=Content-Type content="text/html;charset=utf-8">
		<title>...</title>
		<meta content="blogs" name="keywords">
		<meta content="blogs" name="description">
		<script src="<?=PUBLIC_ACCESS?>/js/ModernizrHtml5Css3.js"></script>
		<link href="<?=PUBLIC_ACCESS?>/css/base.css" type="text/css" rel="stylesheet" />
		<link href="<?=PUBLIC_ACCESS?>/css/index.css" type="text/css" rel="stylesheet" />
		<script src="<?=PUBLIC_ACCESS?>/js/jquery-1.9.1.min.js"></script>
		<script src="<?=PUBLIC_ACCESS?>/js/base.js"></script>
		<!-- for ie 6 7 8 -->
		<!--[if lt IE 9]>
		<style>
			.headerBox, .mainBody{width:1250px;}
		</style>
		<![endif]-->
		<!-- for ie 6 7 8 end-->
		
	</head>
	<body>
		<header class="allHeaderBox">
			<div class="headerBox">
				<div class="Logo"></div>
				<nav class="headerNav">
					<ul></ul>
				</nav>
			</div>
		</header>
		<div class="essayOne mainBody">
			<div class="mainLeft">
				<div class="mainContent">
					<div id="theEssay">
					<!--把文章在这输出-->
						<!--事例，此处可以删掉-->
							<p style="text-align: left;">hello world!~</p><p style="text-align: left;">fdsafdsafsdf</p><p><span style="color: rgb(23, 54, 93);">fdsafsda</span><span style="color: rgb(255, 255, 0);">fdsafsdfsadfsa<span style="color: rgb(255, 0, 0);">fdsfsdafsdfdsfdsfdsaf</span></span></p><p><span style="color: rgb(255, 255, 0);"><span style="color: rgb(255, 0, 0);">fsdfsadfsfsda</span></span></p><p><span style="color: rgb(255, 255, 0);"><span style="color: rgb(255, 0, 0);">fsadf</span></span></p><p><span style="color: rgb(255, 255, 0);"><span style="color: rgb(255, 0, 0);">sadfsdafdsafdsdfdsfdsafsafsafsadfsafsdfdsfasdafsafdsa</span></span><br style="text-align: left;"/></p>
						<!--事例，此处可以删掉end-->
					<!--把文章在这输出end-->
					</div>
				</div>
			</div>
			<aside class="mainRight">
				<section class="clearfix sectionBox sectionOne">
					<h1 class="fR sectionBlank sectionBlankOne">推荐文章</h1>
					<div class="cB blank10"></div>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
				</section>
				<section class="clearfix sectionBox sectionTwo">
					<h1 class="fR sectionBlank sectionBlankTwo">最新回复</h1>
					<div class="cB blank10"></div>
					<div class="smallSliderBox" id="smallSliderBox">
						<article class="detailBox clearfix">
							<img src="<?=PUBLIC_ACCESS?>/img/aside1.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									77
									<br/>
									舞曲跳果舞好好看哦~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img src="<?=PUBLIC_ACCESS?>/img/aside2.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									悠悠
									<br/>
									舞曲跳果舞好好看哦+10086~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img src="<?=PUBLIC_ACCESS?>/img/aside3.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									蚊子
									<br/>
									舞曲跳果舞好好看哦+12520~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img src="<?=PUBLIC_ACCESS?>/img/aside1.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									然娅
									<br/>
									舞曲跳果舞好好看哦+100000~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img src="<?=PUBLIC_ACCESS?>/img/aside2.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									隳月
									<br/>
									舞曲跳果舞好好看哦+20000~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img src="<?=PUBLIC_ACCESS?>/img/aside2.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									杯中蜜
									<br/>
									舞曲跳果舞好好看哦+30000~
								</a>
							</div>
						</article>
					</div>
				</section>
				<section class="clearfix sectionBox sectionThree">
					<h1 class="fR sectionBlank sectionBlankThree">联系我</h1>
					<div class="cB"></div>
					<article class="detailBox clearfix">
						<span class="platformBlank dTbColor fL">平台：</span><a href="#" class="github fL"></a><a href="#" class="weibo fL"></a>
					</article>
					<article class="detailBox">
						<span class="emailBlank dTbColor">邮箱：fdas@163.com</span>
					</article>
				</section>
			</aside>
		</div>
		<footer></footer>
		<!-- 富文本编辑器解析文章 -->		
		
		<script src="<?=PUBLIC_ACCESS?>/js/ueditor.parse.js"></script>
		<script>
			$(function(){
				uParse('#theEssay', {
					rootPath: '<?=PUBLIC_ACCESS?>/js', //ueditor所在的路径，这个要给出，让uparse能找到third-party目录
					//因为需要引入目录下的那些js文件，当然会根据你的编辑数据，按需加载
					liiconpath: 'http://bs.baidu.com/listicon/', //自定义列表标号图片的地址，默认是这个地址
					listDefaultPaddingLeft: '20' //自定义列表标号与文字的横向间距
				})
			})
		</script>

		<!-- 富文本编辑器解析end -->
	</body>
</html>