<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">
	<head>
		<meta http-equiv=Content-Type content="text/html;charset=utf-8">
		<title>...</title>
		<meta content="blogs" name="keywords">
		<meta content="blogs" name="description">
		<script src="<?=PUBLIC_ACCESS?>/js/ModernizrHtml5Css3.js"></script>
		<link href="<?=PUBLIC_ACCESS?>/css/base.css" type="text/css" rel="stylesheet" />
		<link href="<?=PUBLIC_ACCESS?>/css/index.css" type="text/css" rel="stylesheet" />
		<!-- for ie 6 7 8 -->
		<!--[if lt IE 9]>
		<style>
			.headerBox, .mainBody{width:1250px;}
		</style>
		<![endif]-->
		<!-- for ie 6 7 8 end-->
		
		<script src="<?=PUBLIC_ACCESS?>/js/jquery-1.9.1.min.js"></script>
		<script src="<?=PUBLIC_ACCESS?>/js/base.js"></script>
		<script src="<?=PUBLIC_ACCESS?>/js/index.js"></script>
	</head>
	<body>
		<header class="allHeaderBox">
			<div class="headerBox">
				<div class="Logo"></div>
				<nav class="headerNav">
					<ul></ul>
				</nav>
			</div>
		</header>
		<div class="indexOne mainBody">
			<div class="mainLeft">
				<div class="bannerBox" id="bannerBox">
					<section class="bigSliderBoxContent" id="bigSliderBoxContent">
						<article class="contentBox" style="display:block;">
							<header>
								<h2><a class="bTdColor" href="#">这是文章1</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：132次</a><time class="createTime">2013.09.23</time></small>
							</header>
							<p>寇博是一家国内流量排名前十的网站运维负责人，他和他的团24小时队维护着这家日浏览量过亿的网站。十几封报警邮件，意味着全国十几省的用户都出现无法访问该网站的状况。“核心机房又出问题了？”寇博小声默念着，赶忙从一个会议中退席，小跑着上楼，回到运维部的工作大厅。他桌面上的座机正刺耳地响着。“我是客服部的XX，有浙江的用户反映咱们首页上不去了……”“知道了。”寇博立即挂断了电话，朝着正在值班的同事大喊“怎么回事了？”“北京上海机房和CDN(网络加速)反馈都正常，PING了下域名，IP地址的指向不对，可能是DNS的问题。”值班同事回答他可能是DNS的问题。</p>
							<a class="bTdColor" href="#">阅读全文</a>
						</article>
						<article class="contentBox">
							<header>
								<h2><a class="bTdColor" href="#">这是文章2</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：132次</a><time class="createTime">2013.09.23</time></small>
							</header>
							<p>据国外媒体报道，NASA天体物理探索者项目日前确定了两个主要探索方向，即在2017年发射一颗系外行星探测器和安装在国际空间站上的X射线仪，观测来自遥远恒星的能量释放。两个项目具体名称为过境系外行星调查卫星和中子星内部组成探测器，这两个探索任务来自2012年9月提交的四个近期发展项目，NASA决定执行其中的两个最有科学价值的计划。这颗新型系外行星探测器将作为开普勒系外行星探测器的候补，调查范围从类地行星到巨型气态行星，观测距离为太阳系周围最近以及最明亮的恒星（团），主要研究机构为麻省理工学院，首席为乔治·瑞科尔。</p>
							<a class="bTdColor" href="#">阅读全文</a>
						</article>
						<article class="contentBox">
							<header>
								<h2><a class="bTdColor" href="#">这是文章3</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：132次</a><time class="createTime">2013.09.23</time></small>
							</header>
							<p>外出就餐或者是家庭聚餐时，气氛热闹，菜式颇多，总会让人在说说笑中不知不觉的吃进去很多东西，等聚餐结束后才发现自己吃撑了，此时懊悔也来不及了。那不如我们提前做好准备，不让自己有那么好的胃口，不留那么多的位置给那些高脂肪，高热量的食物，你可以选择一个甜甜的大苹果，也可以选择一个甜软适口的木瓜，不仅可以帮助分解一会将要吃紧的过多油脂和脂肪，同时很好的帮助你抑制食欲，避免吃多。这个方法既简单又有效，屡试不爽。</p>
							<a class="bTdColor" href="#">阅读全文</a>
						</article>
						<article class="contentBox">
							<header>
								<h2><a class="bTdColor" href="#">这是文章4</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：132次</a><time class="createTime">2013.09.23</time></small>
							</header>虽然雅虎在过去几个月中的营收并不起眼，但是它的网络流量却独占鳌头。据市场研究公司ComScore称，在2013年12月，雅虎来自台式电脑的美国独立访客数量已超过了1.95亿，超过了谷歌(微博)、微软和Facebook。本周一，ComScore公司推出了在台式电脑上拥有最大流量的美国50大网站排行榜，该榜单显示搜索引擎、新闻网站和社交媒体均吸引了大量的独立访客。在美国，全部桌面互联网用户数量超过了2.24亿。ComScore公司的流量排行榜并未计入移动流量。在雅虎之后，排在第二名的是谷歌，独立用户数1.92亿；排在第三名的是微软，独立用户数1.75亿。在过去几年中，这三家公司一直在前三名徘徊。谷歌通常是第一名，但在2013年7月，雅虎首次夺走了谷歌的桂冠，</p>
							<a class="bTdColor" href="#">阅读全文</a>
						</article>
					</section>
					<div class="positionBox">
						<div class="bigSliderBox" id="bigSliderBox">
							<div class="fullImgBox" id="fullImgBox">
								<a href="#"><img _src="<?=PUBLIC_ACCESS?>/img/BookPreview.jpg" /></a>
								<a href="#"><img _src="<?=PUBLIC_ACCESS?>/img/ShapeHoverEffect.png" /></a>
								<a href="#"><img _src="<?=PUBLIC_ACCESS?>/img/SVGDrawingAnimation.png" /></a>
								<a href="#"><img _src="<?=PUBLIC_ACCESS?>/img/TexturedText.jpg" /></a>
							</div>
							<ul class="oldAnimatBtn clearfix" id="oldAnimatBtn"></ul>
							<div class="halfImgLeft" id="halfImgLeft"></div>
							<div class="halfImgRight" id="halfImgRight"></div>
							<div id="prev" class="btn bTdColor">上一页</div>
							<div id="next" class="btn bTdColor">下一页</div>
						</div>
					</div>
				</div>
				<div class="mainContent">
					<aside class="colorfulTableBox">
						<nav class="colorfulTable">
							<ul>
								<li class="categoryBox categoryOne">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categoryTwo">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categoryThree">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
							</ul>
							<ul id="categoryBox">
								<li class="categoryBox categoryFour categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categoryFive categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categorySix categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categorySeven categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categoryEight categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categoryNine categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
								<li class="categoryBox categoryTen categoryHide">
									<h3><a class="categoryLittleBorder" href="#">CODING</a></h3>
									<a class="categoryLittleHide" href="#">CSS</a>
									<a class="categoryLittleHide" href="#">HTML</a>
									<a class="categoryLittleHide" href="#">JavaScript</a>
									<a class="categoryLittleHide" href="#">Techniques</a>
								</li>
							</ul>
							<div class="categoryBtn dTbColor" id="categoryBtn">更多</div>
						</nav>
					</aside>
					<div class="newEssayBox" id="newEssayBox">
						<article class="contentBox clearfix">
							<a class="contentImg fL" href="#"><img _src="<?=PUBLIC_ACCESS?>/img/ThumbnailGridAnimations1.png"></a>
							<header>
								<h2><a class="bTdColor" href="#">这是文章1</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：123次</a><time class="createTime">2013.08.05</time></small>
							</header>
							<p class="contentMain">这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~<a class="bTdColor" href="#">阅读全文</a></p>
						</article>
						<article class="contentBox clearfix">
							<a class="contentImg fL" href="#"><img _src="<?=PUBLIC_ACCESS?>/img/Unicorn.png"></a>
							<header>
								<h2><a class="bTdColor" href="#">这是文章2</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：123次</a><time class="createTime">2013.08.05</time></small>
							</header>
							<p class="contentMain">这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~<a class="bTdColor" href="#">阅读全文</a></p>
						</article>
						<article class="contentBox clearfix">
							<a class="contentImg fL" href="#"><img _src="<?=PUBLIC_ACCESS?>/img/MediumStylePageTransition.png"></a>
							<header>
								<h2><a class="bTdColor" href="#">这是文章3</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：123次</a><time class="createTime">2013.08.05</time></small>
							</header>
							<p class="contentMain">这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~<a class="bTdColor" href="#">阅读全文</a></p>
						</article>
						<article class="contentBox clearfix">
							<a class="contentImg fL" href="#"><img _src="<?=PUBLIC_ACCESS?>/img/AnimatedSVGIcons.png"></a>
							<header>
								<h2><a class="bTdColor" href="#">这是文章4</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：123次</a><time class="createTime">2013.08.05</time></small>
							</header>
							<p class="contentMain">这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~<a class="bTdColor" href="#">阅读全文</a></p>
						</article>
						<article class="contentBox clearfix">
							<a class="contentImg fL" href="#"><img _src="<?=PUBLIC_ACCESS?>/img/ThumbnailGridAnimations1.png"></a>
							<header>
								<h2><a class="bTdColor" href="#">这是文章5</a></h2>
								<small class="inclineFont"><a class="anchor dTbColor" href="#">作者：steveny</a><a class="clickNum dTbColor" href="#">点击数：123次</a><time class="createTime">2013.08.05</time></small>
							</header>
							<p class="contentMain">这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~这是个测试~大测试~大大的测试~快来看看看吧~<a class="bTdColor" href="#">阅读全文</a></p>
						</article>
						<div class="pageBox">
							<ul class="pageBig clearfix">
								<li class="page"><a href="#" class="pageA">首页</a></li>
								<li class="page"><a href="#" class="pageA">上一页</a></li>
								<li class="page"><a href="#" class="pageA on">1</a></li>
								<li class="page"><a href="#" class="pageA">2</a></li>
								<li class="page"><a href="#" class="pageA">3</a></li>
								<li class="page"><a href="#" class="pageA">4</a></li>
								<li class="page"><a href="#" class="pageA">5</a></li>
								<li class="page"><a href="#" class="pageA">下一页</a></li>
								<li class="page"><a href="#" class="pageA">末页</a></li>
							</ul>
							<ul class="pageMin clearfix">
								<li class="page"><a href="#" class="pageA">上一页</a></li>
								<li class="page"><a href="#" class="pageA">下一页</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<aside class="mainRight">
				<section class="clearfix sectionBox sectionOne">
					<h1 class="fR sectionBlank sectionBlankOne">推荐文章</h1>
					<div class="cB blank10"></div>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
					<article class="detailBox">
						<h2><a class="dTbColor detailBlank" href="#">舞曲今天要跳果舞，大家快来看吧...</a></h2>
						<small class="clearfix essayDetail inclineFont">
							<span class="fL"><a class="dTbColor" href="#">点击数：123次</a></span>
							<time class="fR createTime">2013.09.23</time>
						</small>
					</article>
				</section>
				<section class="clearfix sectionBox sectionTwo">
					<h1 class="fR sectionBlank sectionBlankTwo">最新回复</h1>
					<div class="cB blank10"></div>
					<div class="smallSliderBox" id="smallSliderBox">
						<article class="detailBox clearfix">
							<img _src="<?=PUBLIC_ACCESS?>/img/aside1.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									77
									<br/>
									舞曲跳果舞好好看哦~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img _src="<?=PUBLIC_ACCESS?>/img/aside2.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									悠悠
									<br/>
									舞曲跳果舞好好看哦+10086~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img _src="<?=PUBLIC_ACCESS?>/img/aside3.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									蚊子
									<br/>
									舞曲跳果舞好好看哦+12520~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img _src="<?=PUBLIC_ACCESS?>/img/aside1.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									然娅
									<br/>
									舞曲跳果舞好好看哦+100000~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img _src="<?=PUBLIC_ACCESS?>/img/aside2.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									隳月
									<br/>
									舞曲跳果舞好好看哦+20000~
								</a>
							</div>
						</article>
						<article class="detailBox clearfix">
							<img _src="<?=PUBLIC_ACCESS?>/img/aside2.jpg" class="fL answererImg"/>
							<div class="fL answererDetail">
								<a class="dTbColor" href="#">
									杯中蜜
									<br/>
									舞曲跳果舞好好看哦+30000~
								</a>
							</div>
						</article>
					</div>
				</section>
				<section class="clearfix sectionBox sectionThree">
					<h1 class="fR sectionBlank sectionBlankThree">联系我</h1>
					<div class="cB"></div>
					<article class="detailBox clearfix">
						<span class="platformBlank dTbColor fL">平台：</span><a href="#" class="github fL"></a><a href="#" class="weibo fL"></a>
					</article>
					<article class="detailBox">
						<span class="emailBlank dTbColor">邮箱：fdas@163.com</span>
					</article>
				</section>
			</aside>
		</div>
		<footer></footer>
	</body>
</html>